d

diff --git a/.github/workflows/daily.yml b/.github/workflows/daily.yml
--- a/.github/workflows/daily.yml
+++ b/.github/workflows/daily.yml
@@ -106,10 +106,20 @@ jobs:
           echo "Current working directory: ${{ github.workspace }}"
           ls -alR "${{ github.workspace }}"
 
+      - name: Check for hidden characters in filename
+        run: |
+          filename="index.html"
+          if [[ $(echo "$filename" | od -b | grep -c '  ') -ne 1 ]]; then
+            echo "Error: Hidden characters found in filename: $filename"
+            exit 1
+          else
+            echo "No hidden characters found in filename: $filename"
+          fi
+
       - name: Copy index.html
         run: |
           echo "Current working directory: ${{ github.workspace }}"
-          TEMPLATE_CONTENT=$(cat index.html)
+          TEMPLATE_CONTENT=$(cat ${{ github.workspace }}/index.html)
           UPDATED_CONTENT="${TEMPLATE_CONTENT//{{tip}}/${{ steps.tip_info.outputs.tip }}}"
           if [[ "${{ steps.download_image.outputs.image_exists }}" == "true" ]]; then
             UPDATED_CONTENT="${UPDATED_CONTENT//{{image_section}}/ <div id=\"tip-image\"><img src=\"image.png\" alt=\"Daily tip illustration\" /></div>}"
